<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <meta charset="UTF-8">
    <title>Document</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../static/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" crossorigin="anonymous" type="text/css" href="../../../static/css/base.css"/>
    <link rel="stylesheet" crossorigin="anonymous" type="text/css" href="/static/css/login.css"/>
</head>
<body>
<div class="container no-gutters menu">
    <div class="row no-gutters">
        <div class="col-4 menu-item right-border">Лента</div>
        <div class="col-4 menu-item">О сайте</div>
        <div class="col-4 menu-item left-border">Профиль</div>
    </div>
</div>
<div class="container content">
    <div class="no-gutters dialogs col-8 dialog">
        <div class="interlocutor">
            <img class="avatar" src="https://sun9-61.userapi.com/c624418/v624418543/4fca9/ZlGtFq6vi_4.jpg?ava=1" alt="">
            <div class="interlocutor-name">Ivan ivanov</div>
        </div>
        <div class="row no-gutters messages">
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message rigth-message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message rigth-message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message rigth-message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message rigth-message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message rigth-message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
            <div class="col-12">
                <div class="message">
                    Lorem ipsum
                </div>
            </div>
        </div>
        <form action="" class="row no-gutters message-form">
            <textarea name="" class="col-11 new-message" placeholder="Сообщение"></textarea>
            <button type="submit" class="col-1 send-button" value="">
                <i class="fa fa-paper-plane" aria-hidden="true"></i>
            </button>
        </form>
    </div>
</div>
<div class="container footer">
    КФУ Высшая школа ИТИС<br>
    ©Autogram
</div>
<script src="main.js"></script>
</body>
</html>